/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/_login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRegisterRouteImport } from './routes/_login.register'
import { Route as LoginLoginRouteImport } from './routes/_login.login'
import { Route as AuthenticatedMyListsRouteImport } from './routes/_authenticated/my-lists'
import { Route as AuthenticatedFindFriendsRouteImport } from './routes/_authenticated/find-friends'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFriendsRouteRouteImport } from './routes/_authenticated/friends.route'
import { Route as AuthenticatedFriendsIndexRouteImport } from './routes/_authenticated/friends.index'
import { Route as AuthenticatedFriendsUsernameRouteImport } from './routes/_authenticated/friends.$username'

const LoginRoute = LoginRouteImport.update({
  id: '/_login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRegisterRoute = LoginRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LoginRoute,
} as any)
const LoginLoginRoute = LoginLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedMyListsRoute = AuthenticatedMyListsRouteImport.update({
  id: '/my-lists',
  path: '/my-lists',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFindFriendsRoute =
  AuthenticatedFindFriendsRouteImport.update({
    id: '/find-friends',
    path: '/find-friends',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFriendsRouteRoute =
  AuthenticatedFriendsRouteRouteImport.update({
    id: '/friends',
    path: '/friends',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFriendsIndexRoute =
  AuthenticatedFriendsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFriendsRouteRoute,
  } as any)
const AuthenticatedFriendsUsernameRoute =
  AuthenticatedFriendsUsernameRouteImport.update({
    id: '/$username',
    path: '/$username',
    getParentRoute: () => AuthenticatedFriendsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof AuthenticatedFriendsRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/find-friends': typeof AuthenticatedFindFriendsRoute
  '/my-lists': typeof AuthenticatedMyListsRoute
  '/login': typeof LoginLoginRoute
  '/register': typeof LoginRegisterRoute
  '/friends/$username': typeof AuthenticatedFriendsUsernameRoute
  '/friends/': typeof AuthenticatedFriendsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/find-friends': typeof AuthenticatedFindFriendsRoute
  '/my-lists': typeof AuthenticatedMyListsRoute
  '/login': typeof LoginLoginRoute
  '/register': typeof LoginRegisterRoute
  '/friends/$username': typeof AuthenticatedFriendsUsernameRoute
  '/friends': typeof AuthenticatedFriendsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_login': typeof LoginRouteWithChildren
  '/_authenticated/friends': typeof AuthenticatedFriendsRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/find-friends': typeof AuthenticatedFindFriendsRoute
  '/_authenticated/my-lists': typeof AuthenticatedMyListsRoute
  '/_login/login': typeof LoginLoginRoute
  '/_login/register': typeof LoginRegisterRoute
  '/_authenticated/friends/$username': typeof AuthenticatedFriendsUsernameRoute
  '/_authenticated/friends/': typeof AuthenticatedFriendsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/friends'
    | '/dashboard'
    | '/find-friends'
    | '/my-lists'
    | '/login'
    | '/register'
    | '/friends/$username'
    | '/friends/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/find-friends'
    | '/my-lists'
    | '/login'
    | '/register'
    | '/friends/$username'
    | '/friends'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_login'
    | '/_authenticated/friends'
    | '/_authenticated/dashboard'
    | '/_authenticated/find-friends'
    | '/_authenticated/my-lists'
    | '/_login/login'
    | '/_login/register'
    | '/_authenticated/friends/$username'
    | '/_authenticated/friends/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_login': {
      id: '/_login'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login/register': {
      id: '/_login/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LoginRegisterRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_login/login': {
      id: '/_login/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLoginRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/my-lists': {
      id: '/_authenticated/my-lists'
      path: '/my-lists'
      fullPath: '/my-lists'
      preLoaderRoute: typeof AuthenticatedMyListsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/find-friends': {
      id: '/_authenticated/find-friends'
      path: '/find-friends'
      fullPath: '/find-friends'
      preLoaderRoute: typeof AuthenticatedFindFriendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/friends/': {
      id: '/_authenticated/friends/'
      path: '/'
      fullPath: '/friends/'
      preLoaderRoute: typeof AuthenticatedFriendsIndexRouteImport
      parentRoute: typeof AuthenticatedFriendsRouteRoute
    }
    '/_authenticated/friends/$username': {
      id: '/_authenticated/friends/$username'
      path: '/$username'
      fullPath: '/friends/$username'
      preLoaderRoute: typeof AuthenticatedFriendsUsernameRouteImport
      parentRoute: typeof AuthenticatedFriendsRouteRoute
    }
  }
}

interface AuthenticatedFriendsRouteRouteChildren {
  AuthenticatedFriendsUsernameRoute: typeof AuthenticatedFriendsUsernameRoute
  AuthenticatedFriendsIndexRoute: typeof AuthenticatedFriendsIndexRoute
}

const AuthenticatedFriendsRouteRouteChildren: AuthenticatedFriendsRouteRouteChildren =
  {
    AuthenticatedFriendsUsernameRoute: AuthenticatedFriendsUsernameRoute,
    AuthenticatedFriendsIndexRoute: AuthenticatedFriendsIndexRoute,
  }

const AuthenticatedFriendsRouteRouteWithChildren =
  AuthenticatedFriendsRouteRoute._addFileChildren(
    AuthenticatedFriendsRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedFriendsRouteRoute: typeof AuthenticatedFriendsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFindFriendsRoute: typeof AuthenticatedFindFriendsRoute
  AuthenticatedMyListsRoute: typeof AuthenticatedMyListsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFriendsRouteRoute: AuthenticatedFriendsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFindFriendsRoute: AuthenticatedFindFriendsRoute,
  AuthenticatedMyListsRoute: AuthenticatedMyListsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginLoginRoute: typeof LoginLoginRoute
  LoginRegisterRoute: typeof LoginRegisterRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginLoginRoute: LoginLoginRoute,
  LoginRegisterRoute: LoginRegisterRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
